name: 🚀 Deploy chatwii
on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_dispatch:
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 11.1.3 }
      - uses: actions/setup-node@v4
        with: { node-version: '22.14.0', cache: 'pnpm' }
      - run: pnpm install --frozen-lockfile

      # 🔥 Firebase Hosting Deploy
      - name: 🔥 Firebase Hosting
        if: github.ref_type != 'tag'
        env:
          VITE_BASE: /
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_RECAPTCHA_WEB: ${{ secrets.VITE_RECAPTCHA_WEB }}
          VITE_GEMINI_KEY: ${{ secrets.VITE_GEMINI_KEY }}
        run: |
          pnpm build
          pnpm dlx firebase-tools deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --token "${{ secrets.FIREBASE_TOKEN }}"